/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import model.*;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.util.ArrayList;
import trainingapp.TrainingApp;
/**
 *
 * @author Alejandro
 */
public class WatchAthleteCoachForm extends javax.swing.JFrame {

    /**
     * Creates new form WatchAthleteCoachForm
     */
    // list 1 sportDayList
    // list 2 excercisesList
    // list 3 myExcercisesList
    
    // text dayTextField
    // text monthTextField
    // text yearTextField
    
    // text nameTextField
    // text lengthTextField
    
    // repsButton
    //timeButton
    
    private App model;
    private Coach c;
    private Athlete a;
    private ArrayList<Exercise> startList;
    public WatchAthleteCoachForm() {
        initComponents();
    }
    public WatchAthleteCoachForm(App m, Coach c, Athlete a) {
        initComponents();
        this.model = m;
        this.c = c;
        this.a = a;
        
        this.sportDayList.setListData(a.ViewSportPlan());
        this.myExercisesList.setListData(c.ViewExercises());
        //this.exercisesList.setListData(new ["empty"]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addExercise = new javax.swing.JButton();
        moveUpExercise = new javax.swing.JButton();
        moveDownExercise = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sportDayList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        exercisesList = new javax.swing.JList<>();
        repsButton = new javax.swing.JRadioButton();
        timeButton = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        myExercisesList = new javax.swing.JList<>();
        addMyExercise = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        monthTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        lengthTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sportdays:");

        jLabel2.setText("Exercises:");

        addExercise.setText("Add Exercise");
        addExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExerciseActionPerformed(evt);
            }
        });

        moveUpExercise.setText("Move Up");
        moveUpExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpExerciseActionPerformed(evt);
            }
        });

        moveDownExercise.setText("Move Down");
        moveDownExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownExerciseActionPerformed(evt);
            }
        });

        jLabel3.setText("My exercises:");

        jLabel4.setText("Name:");

        jLabel5.setText("Length:");

        sportDayList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sportDayListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(sportDayList);

        jScrollPane3.setViewportView(exercisesList);

        buttonGroup1.add(repsButton);
        repsButton.setText("Reps");

        buttonGroup1.add(timeButton);
        timeButton.setText("Seconds");

        jScrollPane4.setViewportView(myExercisesList);

        addMyExercise.setText("Add");
        addMyExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMyExerciseActionPerformed(evt);
            }
        });

        jLabel7.setText("Day:");

        dayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextFieldActionPerformed(evt);
            }
        });

        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Month:");

        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Year:");

        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearTextField)
                            .addComponent(jLabel9)
                            .addComponent(dayTextField)
                            .addComponent(monthTextField))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moveUpExercise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveDownExercise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addExercise, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(repsButton)
                                    .addComponent(timeButton)
                                    .addComponent(addMyExercise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lengthTextField)
                                    .addComponent(nameTextField)))))
                    .addComponent(jButton2))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addExercise)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moveUpExercise)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moveDownExercise)
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(repsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeButton)
                        .addGap(18, 18, 18)
                        .addComponent(addMyExercise)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // adds an exercise to athlete exercises
    private void addExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExerciseActionPerformed
        // TODO add your handling code here:
        int exerciseIndex = this.myExercisesList.getSelectedIndex();
        int dateIndex = this.sportDayList.getSelectedIndex();
        //gets indices of both lists
        
        Exercise e = this.c.getMyExercises().get(exerciseIndex);
        // gets exercise from coaches list
        
        SportDay s = this.a.getSportPlan().get(dateIndex);
        // gets sportday from athlete list
        
        
        s.AddExcer(e);
        
        // adds exercise to that sport day
        this.exercisesList.setListData(s.ViewTraining());
        // refreshes what is seen in athletes exercise list
    }//GEN-LAST:event_addExerciseActionPerformed

    private void sportDayListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_sportDayListValueChanged
        // changes wht is seen in the athletes exercise list depending on the sport day chosen
        int dateIndex = this.sportDayList.getSelectedIndex();
        //gets index
        
        SportDay s = this.a.getSportPlan().get(dateIndex);
        // finds chosen sport day
        
        this.exercisesList.setListData(s.ViewTraining());
        // shows current training of that sport day
    }//GEN-LAST:event_sportDayListValueChanged

    private void dayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldActionPerformed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            
            int day = Integer.parseInt(dayTextField.getText());
            if (day <= 0 || day >= 32){
                throw new IllegalArgumentException("Months go from 1 to 31.");
            }
            int month = Integer.parseInt(monthTextField.getText());
            if (month <= 0 || month >= 13){
                throw new IllegalArgumentException("Month go from 1 to 12.");
            }
            int year = Integer.parseInt(yearTextField.getText());
            if ( year < LocalDate.now().getYear()){
                throw new IllegalArgumentException("Year can´t be before this year!");
            }
            if (LocalDate.of(year, month, day).compareTo(LocalDate.now()) < 0){
                throw new IllegalArgumentException("You can't add past days!");
            }
            // checks each textField to see if correct
            
            
            
            SportDay s = new SportDay(day, month, year);
            // creates sport day
            this.a.AddSportDay(s);
            
            // adds Sport day to athlete
            this.sportDayList.setListData(a.ViewSportPlan());
            // refreshes sport day
            
        }
        
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "All data must be integer numbers!");
        }
        catch(IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void addMyExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMyExerciseActionPerformed
        // TODO add your handling code here:
                        try {
            
            String name = nameTextField.getText().toString();
            
            
            int length = Integer.parseInt(lengthTextField.getText());
            BasedOn basedOn;
            if(repsButton.isSelected()){
                basedOn = BasedOn.REPS;
                
            
            }
            else if(timeButton.isSelected()){
                basedOn = BasedOn.TIME;
            
            }
            else{
                throw new IllegalArgumentException("You should select one of the buttons");
            }
            
            // checks buttons are okay
            
            
            Exercise e = new Exercise(name, length, basedOn);
            
            // creates new exercise
            this.c.AddExercise(e);
            
            // adds exercise to coach exercise list
            this.myExercisesList.setListData(c.ViewExercises());
            
            //refreshes list of coach
        }
        
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Length must be integer !");
        }
        catch(IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_addMyExerciseActionPerformed

    private void moveUpExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpExerciseActionPerformed
        // TODO add your handling code here:
        int sportDayIndex = this.sportDayList.getSelectedIndex();
        int exerciseIndex = this.exercisesList.getSelectedIndex();
        
        // gets both indices
        SportDay s = this.a.getSportPlan().get(sportDayIndex);
        // Finds the sport day
        Exercise e = s.getTraining().get(exerciseIndex);
        // Finds the exercise
        s.MoveExerUp(e);
        // moves it up
        this.exercisesList.setListData(s.ViewTraining());
        
    }//GEN-LAST:event_moveUpExerciseActionPerformed

    private void moveDownExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownExerciseActionPerformed
        // TODO add your handling code here:
        int sportDayIndex = this.sportDayList.getSelectedIndex();
        int exerciseIndex = this.exercisesList.getSelectedIndex();
        SportDay s = this.a.getSportPlan().get(sportDayIndex);
        Exercise e = s.getTraining().get(exerciseIndex);
        s.MoveExerDown(e);
        this.exercisesList.setListData(s.ViewTraining());
    }//GEN-LAST:event_moveDownExerciseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        var newGui = new javax.swing.JFrame();
        if(this.c instanceof Coach){
            newGui = new GroupAthletesForm(this.model, this.c);
        }
              
        else{
                JOptionPane.showMessageDialog(this, "Unknown error, this should not happen!");
        }
        newGui.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WatchAthleteCoachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WatchAthleteCoachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WatchAthleteCoachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WatchAthleteCoachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WatchAthleteCoachForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExercise;
    private javax.swing.JButton addMyExercise;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JList<String> exercisesList;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lengthTextField;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JButton moveDownExercise;
    private javax.swing.JButton moveUpExercise;
    private javax.swing.JList<String> myExercisesList;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton repsButton;
    private javax.swing.JList<String> sportDayList;
    private javax.swing.JRadioButton timeButton;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
